# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.2
    hooks:
    -   id: rst-backticks
-   repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
        - id: isort
          name: isort (python)
        - id: isort
          name: isort (cython)
          types: [cython]
        - id: isort
          name: isort (pyi)
          types: [pyi]
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
        -   id: black
